version: 2

jobs:
  setup:
    working_directory: ~/Rise-Vision/widget-common
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-v2-transitional-widgets:0.0.4
    steps:
      - checkout
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: nvm install 7.3.0 && nvm alias default 7.3.0
      - run: npm install
      - run: bower install
      - save_cache:
          key: node-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - components

  test:
    working_directory: ~/Rise-Vision/widget-common
    shell: /bin/bash --login
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: nvm install 7.3.0 && nvm alias default 7.3.0
      - run: node -v
      - run: gulp -v
      - run: NODE_ENV=prod npm run test

  build:
    working_directory: ~/Rise-Vision/widget-common
    shell: /bin/bash --login
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-{{ checksum "package.json" }}
      - run: nvm install 7.3.0 && nvm alias default 7.3.0
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            NODE_ENV=prod npm run build
          else
            NODE_ENV=test npm run build
          fi

workflows:
  version: 2
  workflow1:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
