version: 2

jobs:
  setup:
    working_directory: ~/Rise-Vision/widget-common
    shell: /bin/bash --login
    docker: &DOCKERIMAGE
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
        command: /sbin/init
    steps:
      - checkout
      - restore_cache:
          key: node-cache-v3{{ checksum "package.json" }}
      - run: nvm install 7.3.0 && nvm alias default 7.3.0
      - run: npm install -g gulp bower
      - run: npm install
      - run: bower install
      - save_cache:
          key: node-cache-v3{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - components

  test:
    working_directory: ~/Rise-Vision/widget-common
    shell: /bin/bash --login
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-v3{{ checksum "package.json" }}
      # latest stable chrome
      - run: curl -L -o google-chrome-stable.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run: sudo dpkg -i google-chrome-stable.deb
      # make chrome lxc-friendly
      - run: sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
      - run: nvm install 7.3.0 && nvm alias default 7.3.0
      - run: NODE_ENV=prod npm run test

  build:
    working_directory: ~/Rise-Vision/widget-common
    shell: /bin/bash --login
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-v3{{ checksum "package.json" }}
      - run: nvm install 7.3.0 && nvm alias default 7.3.0
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            NODE_ENV=prod npm run build
          else
            NODE_ENV=test npm run build
          fi

workflows:
  version: 2
  workflow1:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - test
